<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>

            <strong>گزارش غایبین بیش از حد مجاز</strong>
        </h1>
         <?php
        $authNamespace = Zend_Registry::get("authNamespace");
        if ($authNamespace->ACL['dashboard_init'] == 1 || $authNamespace->isAdmin):
            ?>
            <ol class="breadcrumb">
                <li><a href="<?php $this->baseUrl() ?>/dashboard"><i class="fa fa-dashboard"></i> خانه</a></li>
            </ol>
            <?php
        endif;
        ?>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <label class="control-label" >محدوده تاریخ گزارش</label>
        <div class="row"> 

            <div class="col-lg-4">
                <label class="control-label" for="datepickerfrom">از تاریخ</label>
                <div class="input-group">
                    <input type="text"  id="datepickerfrom" placeholder="از تاریخ" class="datepicker form-control">

                </div>
            </div>
            <div class="col-lg-4">
                <label class="control-label" for="datepickerto">تا تاریخ </label>
                <div class="input-group">
                    <input type="text"  id="datepickerto" placeholder="تا تاریخ" class="datepicker form-control">

                </div>
            </div>
            <div class="col-lg-4">
                <label class="control-label" for="datepicker">تعداد غیبت</label>
                <div class="input-group">
                    <input type="number" id="countabsent" value="4" placeholder="تعداد غیبت" class="form-control">

                </div>
            </div>
            <div class="col-lg-3" style="margin-top: 5px">
                <div class="input-group-btn">

                    <button type="button"  onclick="getdata()" class="btn btn-info">دریافت گزارش</button>
                </div><!-- /btn-group -->
            </div>
        </div><!-- /.row -->
        <br/>
        <!-- Main row -->
        <div class="row">

            <section class="col-lg-12 connectedSortable">
                <table id="garddatatbl" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>نام و نام خانوادگی</th>
                            <th>شماره دانشجویی</th>
                            <th>تاریخ</th>
                            <th>تعداد غیبت</th>
                            <th>موبایل</th><!-- <> -->
                            <th>تلفن سرپرست</th>

                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                    <tfoot>
                        <tr>
                            <th>نام و نام خانوادگی</th>
                            <th>شماره دانشجویی</th>
                            <th>تاریخ</th>
                            <th>تعداد غیبت</th>
                            <th>موبایل</th><!-- <> -->
                            <th>تلفن سرپرست</th>


                        </tr>
                    </tfoot>
                </table>




            </section><!-- right col -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<script>
    $(document).ready(function () {
        $(".datepicker").persianDatepicker({format: 'YYYY-MM-DD'});
        $('#garddatatbl').DataTable(
                {
                    dom: 'Blfrtip',
                    buttons: [{
                            extend: 'excel',

                            filename: $('#datepickerfrom').val() + "تا تاریخ " + $('#datepickerfrom').val() + 'گزارش تعداد غیبتها از خوابگاه از  تاریخ '
                        }],
                    destroy: true,
                    lengthMenu: [[5, 10, 20, -1], [5, 10, 20, 'همه']],
                    "language":
                            {
                                url: '/dist/js/datatable/fa.json',
                            }
                });
    }
    );
    function getdata() {
        var datefrom = $('#datepickerfrom').val();
        var dateto = $('#datepickerfrom').val();
        var absentcount = $('#countabsent').val();
        if (datefrom == '' || dateto == '') {
            bootbox.alert({message: 'لطفا تاریخ را وارد کنید', locale: 'fa'});
            return;
        }
        if (absentcount == '') {
            bootbox.alert({message: 'تعداد غیبت را وارد کنید', locale: 'fa'});
            return;
        }
        $('#garddatatbl').DataTable(
                {

                    destroy: true,
                    lengthMenu: [[5, 10, 20, -1], [5, 10, 20, 'همه']],
                    "language":
                            {
                                url: '/dist/js/datatable/fa.json',
                            },
                    processing: true,
                    serverSide: true,
                    dom: 'Blfrtip',
                    buttons: [{
                            extend: 'excel',

                            filename: $('#datepickerfrom').val() + "تا تاریخ " + $('#datepickerfrom').val() + 'گزارش تعداد غیبتها از خوابگاه از  تاریخ '
                        }],

                    ajax: '/report/getgardlist?datefrom=' + $('#datepickerfrom').val() + '&dateto=' +
                            $('#datepickerto').val() + '&countabsent=' + $('#countabsent').val(),
                });
    }
</script>