<section class="vh-100">

    <div class="container-fluid h-custom">
        <div style="border:5px solid #e6e3d7" class="row d-flex justify-content-center align-items-center h-100">
            <p class="col-md-12 col-lg-12 col-xl-12" style="font-size:40px;text-align: center;font-weight: bolder;">
                سامانه کنترل حضور و غیاب خواهران</p>
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="/img/draw2.webp" class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <form action="/index/login" method="post">
                    <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">


                    </div>

                    <!-- Email input -->
                    <div class="form-outline mb-4">
                        <input type="username" name="usr" id="usernamefield" class="form-control form-control-lg"
                            style="boredr :#618eb5 solid 1px !important;text-align:right"
                            placeholder="نام کاربری را وارد کنید" />
                        <label class="form-label" for="usernamefield">نام کاربری </label>

                    </div>

                    <!-- Password input -->
                    <div class="form-outline mb-3">
                        <input type="password" id="passwordfield" name="pwd" class="form-control form-control-lg"
                            style="boredr :#618eb5 solid 1px !important;text-align:right"
                            placeholder="رمز عبور را وارد کنید" />
                        <label class="form-label" for="passwordfield">رمز عبور </label>

                    </div>


                    <div class="text-center text-lg-start mt-4 pt-2">
                        <button type="submit" class="btn btn-primary btn-lg"
                            style="padding-left: 2.5rem; padding-right: 2.5rem;">ورود با سامانه</button>

                    </div>

                </form>
                <?php
                if ($this->error == '1') {
                    ?>
                    <div style="background: #f7acbe;text-align: center;margin-top: 5px;" class="label label-danger">اطلاعات
                        را با دقت وارد کنید</div>
                    <?php
                }
                if ($this->error == '2') {
                    ?>
                    <div style="background: #f7acbe;text-align: center;margin-top: 5px;" class="label label-danger">هشدار
                        امنیتی:زمان استفاده از نرم افزار به پایان رسیده است.لطفا دوباره مشخصات نام کاربری و رمز عبور را وارد
                        کنید</div>
                    <?php
                }
                if ($this->error == '3') {
                    ?>
                    <div style="background: #f7acbe;text-align: center;margin-top: 5px;" class="label label-danger">هشدار
                        امنیتی:
                        شما به این قسمت دسترسی ندارید.با مدیر سیستم تماس بگیرید
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>

</section>

<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Nozha admin panel</title>
    <meta name="description" content="nozha admin panel fully support rtl with complete dark mode css to use. ">
    <meta name=”robots” content="index, follow">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="180x180" href="./img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="./img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="./img/favicon/favicon-16x16.png">
    <link rel="manifest" href="./img/favicon/site.webmanifest">
    <link rel="mask-icon" href="./img/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#2b5797">
    <meta name="theme-color" content="#ffffff">
    <!-- Place favicon.ico in the root directory -->
    <link rel="stylesheet" href="css/normalize.css">
    <link href="./css/fontawsome/all.min.css" rel="stylesheet">
    <link rel="stylesheet"
        href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css"
        integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="css/main.css">
</head>

<body class="">

    <div class="bmd-layout-container bmd-drawer-f-l avam-container animated ">
        <main class="bmd-layout-content">
            <div class="container-fluid">
                <div class="main_wrapper">


                    <!-- form -->

                    <div class="row ">
                        <div class="col-md-5 card shade mw-center mh-center">
                            <img src="./svg/logo.svg" alt="..." class="mw-center " height="130" width="300">
                            <hr class="hr-dashed m-0">
                            <form action="/index/login" method="post">
                                <div class="form-group m-0">
                                    <label for="exampleInputEmail1">Email address</label>
                                    <input type="email" class="form-control" id="exampleInputEmail1"
                                        aria-describedby="emailHelp" placeholder="Enter email">
                                    <small id="emailHelp" class="form-text text-muted">We'll never share your email
                                        with
                                        anyone else.</small>
                                </div>
                                <div class="form-group m-0">
                                    <label for="exampleInputPassword1">Password</label>
                                    <input type="password" class="form-control" id="exampleInputPassword1"
                                        placeholder="Password">
                                </div>
                                <div class="form-check pt-2">
                                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                                </div>
                                <button type="submit" class="btn shade f-primary btn-block">ورود با سامانه</button>
                            </form>
                            <?php
                            if ($this->error == '1') {
                                ?>
                                <div style="background: #f7acbe;text-align: center;margin-top: 5px;"
                                    class="label label-danger">اطلاعات را با دقت وارد کنید</div>
                                <?php
                            }
                            if ($this->error == '2') {
                                ?>
                                <div style="background: #f7acbe;text-align: center;margin-top: 5px;"
                                    class="label label-danger">هشدار امنیتی:زمان استفاده از نرم افزار به پایان رسیده
                                    است.لطفا دوباره مشخصات نام کاربری و رمز عبور را وارد کنید</div>
                                <?php
                            }
                            if ($this->error == '3') {
                                ?>
                                <div style="background: #f7acbe;text-align: center;margin-top: 5px;"
                                    class="label label-danger">هشدار امنیتی:
                                    شما به این قسمت دسترسی ندارید.با مدیر سیستم تماس بگیرید
                                </div>
                                <?php
                            }
                            ?>
                        </div>

                    </div>
                    <!--  -->


                </div>

            </div>
        </main>
    </div>

    </div>



    <script src="js/vendor/modernizr.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script>
        window.jQuery || document.write('<script src="js/vendor/jquery-3.2.1.min.js"><\/script>')
    </script>
    <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js"
        integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous">
        </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js"
        integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous">
        </script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script>
        $(document).ready(function () {
            $('body').bootstrapMaterialDesign();
        });
    </script>
    <script src="js/main.js"></script>

</body>

</html>