<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>

            <small>مدیریت  دستگاه تردد</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="<?php $this->baseUrl() ?>/dashboard"><i class="fa fa-dashboard"></i> خانه</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="modal" id="infodevice">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">اطلاعات دستگاه تردد</h4>
                    </div>
                    <div class="modal-body" id="modalcontent">
                        <p>لطفا شکیبا باشید.یسستم در حال دریافت اطلاعات می باشد</p>
                    </div>
                    <div class="modal-footer">
                        <div id="resultsave"></div>
                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">بستن</button>
                        <button type="button" onclick="savemodal();" class="btn btn-primary">ذخیره</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->       
        <!-- Main row -->
        <a class="btn btn-primary" data-toggle="modal" data-target="#infodevice" onclick="editmodal('')" ><i class="fa fa-fw fa-edit" ></i>افزودن دستگاه جدید</a>

        <div class="row"> 

            <section class="col-lg-12 connectedSortable">
                <table id="devicetbl" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>نوع دستگاه</th>
                            <th>نام دستگاه</th>
                            <th>ای پی</th>
                            <th>پورت </th>
                            <th>موقعیت</th>   
                            <th>شماره دستگاه</th>   
                            <th>وضعیت</th>  
                            <th>عملیات</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                    <tfoot>
                        <tr>
                            <th>نوع دستگاه</th>
                            <th>نام دستگاه</th>
                            <th>ای پی</th>
                            <th>پورت </th>
                            <th>موقعیت</th>   
                            <th>شماره دستگاه</th>    
                            <th>وضعیت</th>  
                            <th>عملیات</th>
                        </tr>
                    </tfoot>
                </table>




            </section><!-- right col -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<script>
    $(document).ready(function () {
        $('#devicetbl').DataTable(
                {
                    "language":
                            {
                                url: '/dist/js/datatable/fa.json',
                            },
                    processing: true,
                    dom: 'Blfrtip', buttons: [{
                            extend: 'excel',
                            autoFilter: true,
                            sheetName: 'گزارش  لیست دستگاهها',
                            filename: new Date() + 'گزارش دستگاههای خوابگاه به تاریخ '
                        }],

                    serverSide: true,
                    ajax: '/device/getinfo',
                    pagingType: 'full_numbers',
                    lengthMenu: [[5, 10, 20, -1], [5, 10, 20, 'همه']],
                });
    });
    function savemodal(id) {
        $.ajax({
            url: "/device/edit",
            method: "POST",
            data: $('#formdevice').serialize(),
        })
                .done(function (html) {
                    $('#resultsave').html(html);
                    setTimeout(function () {
                        $('#resultsave').html("");
                    }, 3000);
                    var table = $('#devicetbl').DataTable().ajax.reload();
                });
    }
    function editmodal(id) {
        $.ajax({
            url: "/device/fetchdata",
            method: "POST",
            data: {ID: id}
        })
                .done(function (html) {
                    $("#modalcontent").html(html);
                });
    }
    function deletemodal(id, name) {
        bootbox.confirm({message: "  حذف  برای  " + name + " مطمئن هستید؟", locale: 'fa', callback: function (result) {
                if (result) {
                    $.ajax({
                        url: "/device/deletedvc",
                        method: "POST",
                        data: {ID: id},
                    })
                            .done(function (result) {
                                bootbox.alert({message: result, locale: 'fa'});
                                var table = $('#devicetbl').DataTable().ajax.reload();

                            });
                }
            }});

    }
</script>