<!-- Content Wrapper. Contains page content -->
<?php $authNamespace = Zend_Registry::get("authNamespace");
if ($authNamespace->ACL['dashboard_init'] == 1 || $authNamespace->isAdmin):
    ?>
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>

                <small>پنل مدیریت</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="<?php $this->baseUrl() ?>/dashboard"><i class="fa fa-dashboard"></i> خانه</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <!-- Small boxes (Stat box) -->
            <div class="modal" id="addrowtaradod">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">اطلاعات  تردد</h4>
                        </div>
                        <div class="modal-body" id="modalcontent">
                            <p>لطفا شکیبا باشید.یسستم در حال دریافت اطلاعات می باشد</p>
                        </div>
                        <div class="modal-footer">
                            <div id="resultsave"></div>
                            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">بستن</button>
                            <button type="button" onclick="savemodalAddRow();" class="btn btn-primary">ذخیره</button>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->       
            <!-- Main row -->

            <div class="row">

                <div class="col-lg-3 col-xs-6">

                    <!-- small box -->
                    <div class="small-box bg-green">
                        <div class="inner">
                            <h3><?php echo ($this->countpersent[0]["TotalRecords"] > 0) ? $this->countpersent[0]["TotalRecords"] : 0 ?> نفر</h3>
                            <p> تعداد حاضرین دیشب</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-stalker"></i>
                        </div>
                        <a href="<?php echo $this->baseUrl() ?>/report/persent?getdate=<?php echo $this->yesterday ?>" class="small-box-footer">اطلاعات بیشتر <i class="fa fa-arrow-circle-left"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-red-gradient">
                        <div class="inner">
                            <h3><?php echo ($this->countabsent[0]["TotalRecords"] > 0) ? $this->countabsent[0]["TotalRecords"] : 0 ?> نفر<sup style="font-size: 20px"></sup></h3>
                            <p>تعداد غائبین دیشب</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-stalker"></i>
                        </div>
                        <a href="<?php echo $this->baseUrl() ?>/report/absent?getdate=<?php echo $this->yesterday ?>" class="small-box-footer">اطلاعات بیشتر <i class="fa fa-arrow-circle-left"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-aqua">
                        <div class="inner">
                            <h3><?php echo ($this->countwikend[0]["TotalRecords"] > 0) ? $this->countwikend[0]["TotalRecords"] : 0 ?> نفر</h3>
                            <p> مرخصی روزانه تا کنون</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-stalker"></i>
                        </div>
                        <a href="<?php echo $this->baseUrl() ?>/report/wikend" class="small-box-footer">اطلاعات بیشتر <i class="fa fa-arrow-circle-left"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-yellow">
                        <div class="inner">
                            <h3><?php echo ($this->countwikendHourly[0]["TotalRecords"] > 0) ? $this->countwikendHourly[0]["TotalRecords"] : 0 ?> نفر</h3>
                            <p>مرخصی ساعتی امروز</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-stalker"></i>
                        </div>
                        <a href="<?php echo $this->baseUrl() ?>/report/wikendhourly" class="small-box-footer">اطلاعات بیشتر <i class="fa fa-arrow-circle-left"></i></a>
                    </div>
                </div><!-- ./col -->

            </div><!-- /.row -->
            <div class="row" style="margin-bottom: 5px">
                <div class="col-lg-1">

                    <div class="input-group">

                        <div class="input-btn">
                            <button type="button"  onclick="getonlinedata()" class="btn btn-warning">بروزرسانی</button>
                        </div><!-- /btn-group -->

                    </div>

                </div>
                <div class="col-lg-1">

                    <div class="input-group">

                        <div class="input-btn">
                            <button type="button"  data-toggle="modal" data-target="#addrowtaradod" onclick="editmodalAddeow()" class="btn btn-warning">افزودن تردد دستی</button>
                        </div><!-- /btn-group -->
                    </div>
                </div>
            </div><!-- /.row -->
            <!-- Main row -->
            <div class="row">

                <section class="col-lg-12 connectedSortable">
                    <table id="onlineTrafic" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>

                                <th>نام و نام خانوادگی</th>
                                <th>کد دانشجویی</th>
                                <th>تاریخ</th>
                                <th>ساعت</th>
                                <th>تردد مرخصی روزانه</th>
                                <th>تردد مرخصی ساعتی</th>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>نام و نام خانوادگی</th>
                                <th>کد دانشجویی</th>
                                <th>تاریخ</th>
                                <th>ساعت</th>
                                <th>تردد مرخصی روزانه</th>
                                <th>تردد مرخصی ساعتی</th>
                            </tr>
                        </tfoot>
                    </table>
                </section><!-- right col -->
            </div><!-- /.row (main row) -->

        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
    <script>
        const interval = null;

        $(document).ready(function () {
            $('#onlineTrafic').DataTable(
                    {

                        destroy: true,
                        "language":
                                {
                                    url: '/dist/js/datatable/fa.json',
                                },
                        processing: true,
                        dom: 'Blfrtip', buttons: ['excel'],

                        serverSide: true,
                        order: [[2, 'desc'], [3, 'desc']],
                        lengthMenu: [[5, 10, 20, -1], [5, 10, 20, 'همه']],

                        ajax: '/dashboard/getonlinetrafic',
                    });
            interval = setInterval(Function("getonlinedata();"), 60000);
        });
        function sync() {

        }

        $("#button1").click(function () {
            document.getElementById('loadarea').src = '/dashboard/sync';
        });
        $("#button2").click(function () {
            document.getElementById('loadarea').src = '';
        });
        function getonlinedata() {
            var table = $('#onlineTrafic').DataTable().ajax.reload();
            return;
        }
        function regData(code, scode, wikend, date, time, val) {
            clearInterval(interval);
            var type = "نامشخص";
            var action = "حذف";
            if (val == 2) {
                type = "روزانه";
            } else if (val == "3") {
                type = "ساعتی";
            }
            if (wikend == 1 || wikend == true) {
                action = "ثبت";
            }
            bootbox.confirm({message: action + " مرخصی  " + type + " برای   " + code + " مطمئن هستید؟", locale: 'fa', callback: function (result) {
                    if (result) {
                        $.ajax({
                            url: "/dashboard/editkindtrafic",
                            method: "POST",
                            data: {code: code, scode: scode, wikend: wikend, date: date, time: time, kindtrafic: val}
                        })
                                .done(function (result) {
                                    bootbox.alert({message: result, locale: 'fa'});

                                });
                    }
                }});
            interval = setInterval(Function("getonlinedata();"), 30000);
        }
        function editmodalAddeow(id) {
            $.ajax({
                url: "/dashboard/addrow",
                method: "POST"
            })
                    .done(function (html) {
                        $("#modalcontent").html(html);
                    });
        }
        function savemodalAddRow(id) {
            $.ajax({
                url: "/dashboard/addrowsave",
                method: "POST",
                data: $('#formaddrow').serialize(),
            })
                    .done(function (html) {
                        $('#resultsave').html(html);
                        setTimeout(function () {
                            $('#resultsave').html("");
                        }, 3000);
                        var table = $('#onlineTrafic').DataTable().ajax.reload();
                    });
        }

    </script>
<?php endif; ?>