<form id="formuser" method="post" action="saveaddusers" class="form-horizontal">
    <div class="box-body">
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">نام کاربری</label>
            <div class="col-sm-10">
                <input type="text" name="name"  autocomplete="off" class="form-control" value="" id="name" placeholder="نام کاربری">
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">رمز عبور</label>
            <div class="col-sm-10">
                <input type="password" name="password"  autocomplete="off" class="form-control" value="" id="pwd" >
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">تکرار رمز عبور</label>
            <div class="col-sm-10">
                <input type="password"  autocomplete="off" class="form-control" value="" id="duppwd" >
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label class="control-label" for="active">
                        <input type="checkbox" id="active" checked='checked' value="1" name="active"> 
                        فعال</label>
                </div>
            </div>
        </div>   
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label class="control-label" for="force">
                        <input type="checkbox" id="force" checked='checked' value="1" name="force"> 
                        اجبار در گزارش غیبت</label>
                </div>
            </div>
        </div> 
    </div><!-- /.box-body -->

</form>
