<form id="formuser" method="post" action="savepasswordusers"  autocomplete="off" class="form-horizontal">

     <input type="hidden" name="name" value="<?php echo $this->user['name']?>"></input>
    <div class="box-body">
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">نام کاربری</label>
            <div class="col-sm-10">
                <input type="text" readonly="readonly"  autocomplete="off"  class="form-control" value="<?php echo $this->user["name"]?>" id="name" placeholder="نام کاربری">
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">رمز عبور  قبلی</label>
            <div class="col-sm-10">
                <input type="password" name="oldpassword"  autocomplete="off"  class="form-control" value="" id="oldpwd" >
            </div>
        </div>
           <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">رمز عبور  جدید</label>
            <div class="col-sm-10">
                <input type="password" name="newpassword"  autocomplete="off"  class="form-control" value="" id="pwd" >
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label"> تکرار رمز عبور جدید</label>
            <div class="col-sm-10">
                <input type="password" name="reapetpassword"  autocomplete="off"  class="form-control" value="" id="duppwd" >
            </div>
        </div>        
    </div><!-- /.box-body -->

</form>
