<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>سامانه کنترل حضور و غیاب خواهران</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.4 -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/bootstrap/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/font-awesome.min.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/buttons.dataTables.min.css">
        <!-- Ionicons 2.0.0 -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/ionicons.min.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/dist/js/datatable/dataTables.bootstrap.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/dist/css/AdminLTE.css">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/dist/css/skins/_all-skins.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/plugins/iCheck/flat/blue.css">
        <!-- Morris chart -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/plugins/morris/morris.css">
        <!-- jvectormap -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
        <!-- Date Picker -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/plugins/datepicker/datepicker3.css">
        <!-- Daterange picker -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/plugins/daterangepicker/daterangepicker-bs3.css">
        <!-- bootstrap wysihtml5 - text editor -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/dist/fonts/fonts-fa.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/dist/css/bootstrap-rtl.min.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/dist/css/rtl.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/bootstrap-datepicker.min.css" />
        <!-- jQuery 2.1.4 -->
        <script src="<?php echo $this->baseUrl() ?>/dist/js/jquery-3.5.1.js"></script>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="skin-blue sidebar-mini">
        <div class="wrapper">

            <header class="main-header">
                <!-- Logo -->
                <a href="https://khc.ui.ac.ir" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><b>khc</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>دانشکده ریاضی و کامپیوتر خوانسار</span>
                </a>
                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">منوی کناری</span>
                    </a>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- Messages: style can be found in dropdown.less-->
                            <li><a href="https://khc.ui.ac.ir/" target="_self"><img src="<?php echo $this->baseUrl() ?>/img/arm.png"  title="دانشکده ریاضی و کامپیوتر خوانسار" alt="دانشکده ریاضی و کامپیوتر خوانسار" class="img-responsive" width="130" height="25" border="0"> </a>
                            </li>
                          
                            <li class="dropdown messages-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-envelope-o"></i>
                                    <span class="label label-success">0</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="header">شما پیغامی ندارید</li>
                                    <li>
                                        <!-- inner menu: contains the actual data -->
                                        <ul class="menu">

                                        </ul>
                                    </li>
                                    <li class="footer"><a href="#">مشاهده همه پیامها</a></li>
                                </ul>
                            </li>
                            <!-- Notifications: style can be found in dropdown.less -->
                            <li class="dropdown notifications-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-bell-o"></i>
                                    <span class="label label-warning">0</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="header">شما نکته یاداوری ندارید</li>
                                    <li>
                                        <!-- inner menu: contains the actual data -->
                                        <ul class="menu">

                                        </ul>
                                    </li>
                                    <li class="footer"><a href="#">مشاهده همه</a></li>
                                </ul>
                            </li>
                            <!-- Tasks: style can be found in dropdown.less -->

                            <li class="">
                                <a href="<?php echo $this->baseUrl() ?>/index/logout" alt='خروج'>
                                    <i title='خروج' style='font-size:30px;color:red' class="fa fa-power-off"></i>                                   
                               
                                </a>


                            </li>

                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- Sidebar user panel -->
                    <div class="user-panel">
                        <div class="pull-right image">
                            <img src="<?php echo $this->baseUrl() ?>/img/download.jpg" class="img-circle" alt="User Image">
                        </div>
                        <div class="pull-left info">
                            <p><?php
                                $authNamespace = Zend_Registry::get("authNamespace");
                                echo 'کاربر  ' . $authNamespace->name;
                                ?></p>

                        </div>
                    </div>
                    <!-- search form -->
                    <form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="جستوجو ...">
                            <span class="input-group-btn">
                                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                    <!-- /.search form -->
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <?php
                    $authNamespace = Zend_Registry::get("authNamespace");
                    echo $authNamespace->menu;
                    ?>   
                </section>
                <!-- /.sidebar -->
            </aside>
            <?php echo $this->layout()->content; ?>

            <footer class="main-footer">
                <div class="pull-left hidden-xs">
                    <b>Version</b> 1.0.0
                </div>
                <strong>برنامه نویس :علی احمد میرزایی</a>.</strong> 
            </footer>


        </div><!-- ./wrapper -->


        <!-- jQuery UI 1.11.4 -->
        <script src="<?php echo $this->baseUrl() ?>/dist/js/jquery-ui.min.js"></script>
        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script>
            $.widget.bridge('uibutton', $.ui.button);
        </script>
        <!-- Bootstrap 3.3.4 -->
        <script src="<?php echo $this->baseUrl() ?>/bootstrap/js/bootstrap.min.js"></script>
        <!-- Morris.js charts -->
        <script src="<?php echo $this->baseUrl() ?>/dist/js/raphael-min.js"></script>

        <!-- Sparkline -->
        <script src="<?php echo $this->baseUrl() ?>/plugins/sparkline/jquery.sparkline.min.js"></script>
        <!-- jvectormap -->
        <script src="<?php echo $this->baseUrl() ?>/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
        <!-- jQuery Knob Chart -->
        <script src="<?php echo $this->baseUrl() ?>/plugins/knob/jquery.knob.js"></script>
        <!-- daterangepicker -->
        <script src="<?php echo $this->baseUrl() ?>/dist/js/moment.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/plugins/daterangepicker/daterangepicker.js"></script>
        <!-- datepicker -->
        <script src="<?php echo $this->baseUrl() ?>/plugins/datepicker/bootstrap-datepicker.js"></script>
        <!-- Bootstrap WYSIHTML5 -->
        <script src="<?php echo $this->baseUrl() ?>/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
        <!-- Slimscroll -->
        <script src="<?php echo $this->baseUrl() ?>/plugins/slimScroll/jquery.slimscroll.min.js"></script>
        <!-- FastClick -->
        <script src="<?php echo $this->baseUrl() ?>/plugins/fastclick/fastclick.min.js"></script>
        <!-- AdminLTE App -->
        <script src="<?php echo $this->baseUrl() ?>/dist/js/app.min.js"></script>

        <!-- AdminLTE for demo purposes -->
        <script src="<?php echo $this->baseUrl() ?>/dist/js/demo.js"></script>

        <script src="<?php echo $this->baseUrl() ?>/dist/js/datatable/jquery.dataTables.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/dist/js/datatable/dataTables.bootstrap.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/dist/js/datatable/dataTables.buttons.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/dist/js/datatable/buttons.html5.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/dist/js/bootbox/bootbox.all.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/dist/js/jszip.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/dist/js/pdfmake.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/dist/js/vfs_fonts.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/dist/js/bootstrap-datepicker.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/dist/js/bootstrap-datepicker.fa.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/dist/js/autocomplete.js"></script>


    </body>
</html>
