<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>

            <small>مدیریت اطلاعات دانشجو</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="<?php $this->baseUrl() ?>/dashboard"><i class="fa fa-dashboard"></i> خانه</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="modal" id="infostudent">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">اطلاعات دانشجو</h4>
                    </div>
                    <div class="modal-body" id="modalcontent">
                        <p>لطفا شکیبا باشید.یسستم در حال دریافت اطلاعات می باشد</p>
                    </div>
                    <div class="modal-footer">
                        <div id="resultsave"></div>
                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">بستن</button>
                        <button type="button" onclick="savemodal();" class="btn btn-primary">ذخیره</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->       
        <!-- Main row -->
        <div class="row"> 
            <section class="col-lg-12 connectedSortable">
                <table id="example" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>

                            <th>نام و نام خانوادگی</th>
                            <th>کد دانشجویی</th>
                            <th>کد</th>
                            <th>ساکن خوابگاه</th>
                            <th>مرخصی </th>
                            <th>عملیات</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                    <tfoot>
                        <tr>

                            <th>نام و نام خانوادگی</th>
                            <th>کد دانشجویی</th>
                            <th>کد</th>
                            <th>ساکن خوابگاه</th>
                            <th>مرخصی </th>
                            <th>عملیات</th>
                        </tr>
                    </tfoot>
                </table>




            </section><!-- right col -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<script>
    $(document).ready(function () {
        $('#example').DataTable(
                {
                    "language":
                            {
                                url: '/dist/js/datatable/fa.json',
                            },
                    processing: true,
                    serverSide: true,
                    ajax: '/manager/getinfo',
                    dom: 'Blfrtip',
                    buttons: [{
                            extend: 'excel',
                            autoFilter: true,
                            sheetName: 'گزارش  لیست دانشجویان',
                            filename: new Date() + 'گزارش دانشجویان خوابگاه به تاریخ '
                        }],

                    paging: true,
                    lengthMenu: [[5, 10, 20, -1], [5, 10, 20, 'همه']],
                });
    });
    function savemodal(id) {
        $.ajax({
            url: "/manager/edit",
            method: "POST",
            data: $('#formstudent').serialize(),
        })
                .done(function (html) {
                    $('#resultsave').html(html);
                    setTimeout(function () {
                        $('#resultsave').html("");
                    }, 3000);
                    var table = $('#example').DataTable().ajax.reload();
                });
    }
    function editmodal(id) {
        $.ajax({
            url: "/manager/fetchdata",
            method: "POST",
            data: {code: id}
        })
                .done(function (html) {
                    $("#modalcontent").html(html);
                });
    }
    function deletemodal(id) {
        $('#modal').modal();
    }



</script>